server:
  port: 8080

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://******:3306/*****?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: "******"
    password: "******"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss+08:00
    default-property-inclusion: non_null

#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.aliyuncs.aui.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 10

# pop配置
biz:
  openapi:
    access:
      key: "*********"
      secret: "*********"
  live_im:
    app_id: TY3****
  live_stream:
    push_url: push.*****.vip
    pull_url: pull.*****.vip
    push_auth_key: zJl4******
    pull_auth_key: mDZs********
    app_name: live
    auth_expires: 604800
  live_mic:
    app_id: 7c61********
    app_key: c461b*********
  ram:
    access_key_id: LTAI5*********
    access_key_secret: NLgHO********
  upload:
    role_arn: acs:ram::*******
    region: cn-shanghai
    bucket: *****
    base_path: /***
http:
  cors:
    host: "*"